# ══════════════════════════════════════════════════════════════
# Configuração do Servidor
# ══════════════════════════════════════════════════════════════
#server.port=8080

# ══════════════════════════════════════════════════════════════
# Configuração do Banco de Dados (MySQL)
# ══════════════════════════════════════════════════════════════
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=jnlGjeJfWctwxhulFTnvQiaAoSxmEqFZ
#spring.datasource.url=jdbc:mysql://localhost:3306/biblioteca_db
#spring.datasource.username=root
#spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ══════════════════════════════════════════════════════════════
# JPA / Hibernate
# ══════════════════════════════════════════════════════════════
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Configura��es de E-mail (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
